[package]
name = "std"
version = "0.1.0"
edition = "2024"

[dependencies]
common = { path = "../common" }

[package.metadata.bootimage]
test-args = [
    "-device", "isa-debug-exit,iobase=0xf4,iosize=0x04",
    "-serial", "stdio",
    "-display", "none"
]
test-success-exit-code = 33   # (0x10 << 1) | 1
test-timeout = 5              # (in seconds)
